framework_response.go

Previously would send down null if no data was ever added since the interface{} was never initialized.
Now sends an empty array.

EVG-5785: Return an empty array for no data

---

server.go

This was causing false grip error logs in Jasper tests whenever the REST service was closed (6fe16b722988839f88a1a40537e06e88366735d3).

Remove error log from ListenAndServe if it's due to Shutdown

---

acl/roles.go
acl/roles_test.go
auth_interfaces.go
rolemanager/role_manager.go
rolemanager/role_manager_test.go

- create the concept of a permission registry, where valid permission keys are specified
- enforce that roles can't be created if they have an unregistered permission key
- fix an unrelated bug where inserting a new role returns a database error

EVG-6375 add permission registry

---

auth_interfaces.go
rolemanager/role_manager.go
rolemanager/role_manager_test.go

- Assume that scopes always have all their relevant resources listed within them
- Add a method to find a role with given permissions. This isn't used yet, but will be used by MANA to find an existing role that matches what permissions the user requests

EVG-6380 add method to find role with given permissions

---

auth_basic_test.go
auth_interfaces.go
auth_mock_test.go
auth_user_basic.go
auth_user_basic_test.go
ldap/ldap.go
ldap/ldap_test.go
okta/okta.go
rolemanager/role_manager_test.go
usercache/cache_test.go
usercache/external.go
usercache/inmemory.go
usercache/interface.go
util/string.go
util/string_test.go

JIRA: https://jira.mongodb.org/browse/MAKE-1093
This is just the refactor. Using the cache in the Okta user manager will come in a subsequent PR.
* Refactor LDAP user cache to its own package.
* Add access and refresh tokens to User interface and implementations.

MAKE-1093: refactor user cache and add access/refresh tokens

---

auth_interfaces.go
auth_mock_test.go
auth_user_basic.go
ldap/ldap_test.go
middleware_auth.go
rolemanager/role_manager_test.go

- Add the concept of default roles, which are given to users that are not logged in. This should allow us to remove the RequiresProjectViewPermission middleware in evergreen
- Simplify the signature of user.HasPermission so that it only returns a bool

EVG-7020 add default permissions

---

okta/okta.go

JIRA: https://jira.mongodb.org/browse/MAKE-1083
https://jira.mongodb.org/browse/MAKE-1093
* Use cache to implement some required functions (e.g. `GetUserByToken`, `GetUserByID`, `ClearUserToken`).
* Add functions to get/put HTTP clients.
* Add some required fields for authorizing user (`CreationOptions.UserGroup`).
* Add stubs for validating tokens (will  be done later), validate user groups before authentication passes.
* Store temp cookies and login cookies.

MAKE-1083, MAKE-1093: use login cache and implement logout

---

ldap/ldap.go

JIRA: https://jira.mongodb.org/browse/MAKE-1129
`url.Parse()` interprets `host:port` format as having a scheme of `host` since it has a colon. We don't include a scheme in the LDAP settings, so we have to check this.

MAKE-1129: check for ambiguous URL scheme

---

middleware_auth_user.go
okta/okta.go

JIRA: https://jira.mongodb.org/browse/MAKE-1131
If we don't specify the login cookie domain when we clear it, it will default to this domain, which can differ from the domain the cookie is actually set for (i.e. .mongodb.com for us).
I also removed the login redirect attempt because of this cookie clearing problem, because the duplicate name cookies for staging caused the wrong cookie to always be read and login couldn't succeed without setting the cookie.

MAKE-1131: specify cookie domain

---

middleware_auth_user.go
okta/okta.go
okta/okta_test.go

JIRA: https://jira.mongodb.org/browse/MAKE-1139
According to IT, the check for whether or not the user logging in is an employee is done on the Okta side. Therefore, we don't have to check the user's groups and we can reduce the number of Okta requests when we authenticate and reauthorize. If `ValidateGroups` is set, it will check the user's groups (i.e. do the equivalent of the LDAP employee group check); otherwise, it just checks that the ID token is valid and matches the user ID.

MAKE-1139: remove user group checking

---

app_resolve.go
app_resolve_test.go
app_routing.go
app_routing_test.go
proxy.go
proxy_test.go

- Add PrefixRoute routes that match everything beginning with a prefix.
- StripSourcePrefix (in ProxyOptions) will remove the matched prefix/route but leave the rest of the path (which should only matter for a prefix route)
- Added a remote scheme option to ProxyOptions to use a different protocol (such as http) when talking to the remote server

EVG-7149 reverse-proxy changes for code-server

---

auth_basic_test.go
auth_user_basic.go
auth_user_basic_test.go
ldap/ldap.go
ldap/ldap_test.go
okta/okta.go
okta/okta_test.go
proxy.go
rolemanager/role_manager_test.go
user_service_basic.go
user_service_basic_test.go
usercache/cache_test.go

JIRA: https://jira.mongodb.org/browse/MAKE-1169
* Export BasicUsers and use builder instead of long list of arguments to construct it.
* Make basic user manager accept BasicUsers as input.

MAKE-1169: improve usability of basic user and manager

---

auth_mock_test.go
middleware_auth_test.go
middleware_auth_user_test.go
user_service_multi.go
user_service_multi_test.go

JIRA: https://jira.mongodb.org/browse/MAKE-1164
The plan for Evergreen is to have the Okta user manager be the real manager and the basic user manager will be read-only so we can't add/remove/reauthorize users via the UserManager interface.
* Add multi user manager that performs the op until it reaches the first success.
* Read-write managers can perform all UserManager operations.
* Read-only managers can get users by id/token, but can't create/delete/reauthorize users.

MAKE-1164: implement multi user manager

---

cached/user_service_cached.go

JIRA: https://jira.mongodb.org/browse/MAKE-1178
This one is kind of weird, but basically the new user manager is just a thin wrapper around requests to the cache (i.e. the database). We have to do this because I found out during testing that the only users we can use in the Evergreen API are `user.DBUser`s.

MAKE-1178: make cache-only user manager

---

middleware_auth_user.go

JIRA: https://jira.mongodb.org/browse/MAKE-1183
Lots of requests going through user middleware don't have any username attached to them, which produces a lot of noisy logs since you can't call GetUserByID with an empty ID.

MAKE-1183: check for empty user from header

---

middleware_auth_user.go

JIRA: https://jira.mongodb.org/browse/MAKE-1184
This is mostly because having the same cookie for staging and prod could present both cookies, but in no guaranteed order, so people who use both might have problems authing into one of them.

MAKE-1184: check all cookies matching the name

---

middleware_grip.go
middleware_grip_test.go

The http.ErrAbortHandler is a [sentinel error](https://github.com/golang/go/blob/844bf11ecd362e50e62a81c93aa2ac602de59adc/src/net/http/server.go#L1742) to suppress go server logging of the error. 
Since our middleware recovers this panic in the HandlerFunc before it makes it back up to the server we should at least log at a lower level.

EVG-8182 Log http.ErrAbortHandler errors at a lower level

---

okta/okta.go
okta/okta_test.go

JIRA: https://jira.mongodb.org/browse/EVG-12629
If the response body we receive from Okta includes an error message, return that error message. Before, we wouldn't consider the response body if it returned non-200, but the body often contains the error message encoded in JSON. The body error message lets us know if the refresh token is expired, in which case the only way to get a new one is to log into Okta again (i.e. log into the UI).

EVG-12629: return the error message from Okta server

---

app_resolve.go

JIRA: https://jira.mongodb.org/browse/EVG-14757
I can't think of a reason this should not be turned on by default.

EVG-14757: Use encoded URL paths

---

okta/okta.go
okta/okta_test.go

Jira: https://jira.mongodb.org/browse/EVG-14886
In our Okta authentication, we've been using `/oauth2/v1` routes to make requests to Okta. The route that we use to authorize users (i.e. the one that shows the Okta login page to the user) returns special tokens that allow users to use the REST API without an associated session in the website. However, these routes return tokens that expire after 100 days, which is frustrating to users, because you get 401 unauthorized responses from the API and you have to re-login to the Evergreen UI.
Switching from using `/oauth2/v1` to `/oauth2/default/v1` will give us tokens that never expire, so you can use the Evergreen CLI without the 100-day expiration. **As a consequence of this, we're going to have to log everyone out of Evergreen because the …

EVG-14886: use Okta default authorization server

---

parsing.go
parsing_test.go

[EVG-14923](https://jira.mongodb.org/browse/EVG-14923)
A change was recently made in gimlet  to allow encoded paths in the url when setting up the initial mux router: evergreen-ci/gimlet@5fbd893. This caused methods in the middleware to break because gimlet.getVars(r) would now retrieve encoded task Ids, resulting in 404 errors. There is a comment above getVars in the codebase saying that it returns decoded parameters but that is no longer the case due to the linked change. Change has been added to decode parameters when calling getVars.

EVG-14923: Decode strings for all arguments passed to URL

---

app_routing.go
app_routing_test.go

Adding these methods to allow us to programmatically access gimlet route values. 
This is a requirement for https://github.com/evergreen-ci/evergreen/pull/5053

EVG-15384 Add accessor methods to gimlet routes

---

vendor/github.com/urfave/negroni/static.go

Double slash seems to have been causing an open redirect issue, see ticket for details. We now make sure that the path does not have any leading //, which would cause certain URLs with special characters to redirect to an external site.

EVG-15423: remove double slashes in URL to prevent open redirect issues

---

middleware_grip.go

[EVG-15787](EVG-15787)
I considered also including [GetVars(r)](https://github.com/evergreen-ci/gimlet/blob/bcf5586bf67539400214d4f562ed27040458aa61/parsing.go#L21) but I decided it wasn't worth adding to the message since we already have the path and the vars are part of the path.
I considered adding them to only one of the start and finish messages, but I figured both would be useful.
I considered checking the size of vars before logging it to make sure we're not logging to much to Splunk, but I think it's unlikely enough that we can wait and see if it's a problem.

EVG-15787 add params to logs

---

middleware_auth_user.go
middleware_grip.go
middleware_grip_test.go

[EVG-14198](https://jira.mongodb.org/browse/EVG-14198)
If the user is authenticated we'd like to include the username in the log. We attempted this previously (#87) but it wasn't getting included in the log message. 
This confused me for a while. After investigating, I think the reason is that although the user middleware [adds the user to its request's context](https://github.com/evergreen-ci/gimlet/blob/bcf5586bf67539400214d4f562ed27040458aa61/middleware_auth_user.go#L86-L88) the request of the previous caller in the middleware chain is unchanged so [when we go to log it](https://github.com/evergreen-ci/gimlet/blob/bcf5586bf67539400214d4f562ed27040458aa61/middleware_grip.go#L142) the user is still nil. The question, though, is: why is the request unchanged in the caller? Doesn't it …

EVG-14198 log usernames

---

app_merge.go
app_merge_test.go
go.mod
go.sum

[EVG-19186](https://jira.mongodb.org/browse/EVG-19186)
Modify the `MergeApplications` function to take a preconfigured router. I want to be able to pass in a router with the OTEL instrumentation added. I don't think we'll necessarily want the tracer for every application that uses gimlet 😄, although it just noops if the tracer isn't configured.

EVG-19186 accept a configured router

---

framework.go

This automatically logs the response body of all 500+ status code requests, which allows us to inspect the error message directly in Splunk
Hardcoded a route to return an internal service error and confirmed the error message was in Splunk

DEVPROD-6570 Grip error on >500 codes

---

go.mod
go.sum
middleware_auth_user.go
middleware_auth_user_test.go

[DEVPROD-11549](https://jira.mongodb.org/browse/DEVPROD-11549)
This PR allows fetching a user by their JWT. This will be used in a forthcoming PR on Evergreen.
The go-oidc library is the one Kanopy uses internally, though we can't use v3 on go 1.20.

DEVPROD-11549 validate JWTs

---

middleware_static_auth.go

The current static content serving middleware is un-authed.  Added a new middleware that uses the same code as Negroni's static content middleware, but with user authentication. Change has to be here and not in Negroni to prevent cyclical dependency. Will update Evergreen at [this line](https://github.com/evergreen-ci/evergreen/blob/88b2a45ac93a622056e501dd6471a6f2469bbb86/service/service.go#L49) afterwards
Confirmed that urls such as https://evergreen-staging.corp.mongodb.com/package.json are no longer accessible from the public web with this change.

DEVPROD-11692 Add auth-checking for serving static content

---

framework_response_simple.go

DEVPROD-14866
When we were returning err.Error, that's just the cause. Returning in.Error will return the full context of the error (all information possible)

DEVPROD-14866 Return full error rather than unwrapped cause error
